# Server Configuration
server_address: "127.0.0.1:9000"
num_rounds: 5
min_clients: 2

# Federated Learning Configuration
strategy: "fedavg"
fraction_fit: 1.0  # Tỷ lệ clients tham gia training
fraction_evaluate: 1.0  # Tỷ lệ clients tham gia evaluation

# Client Training Configuration
local_epochs: 3
batch_size: 32
learning_rate: 0.01

# Model Configuration
model:
  name: "resnet"
  num_classes: 100

# Data Configuration
data_type: "folder" # "folder" type for Resnet or "npz" for  MLP, Mr.Vu logic
dataset_url: "https://github.com/AISeedHub/FedFace/releases/download/model/dataset.zip"
full_data_path: "src/use_cases/face_detection/data/dataset"
train_data_path: "src/use_cases/face_detection/data/dataset/train"
test_data_path: "src/use_cases/face_detection/data/dataset/test"
distributed_data_path: "src/use_cases/face_detection/distributed_data" # Path to save distributed data among clients
num_clients: 2
non_iid: true
alpha: 0.5  # Dirichlet distribution parameter for non-IID data splitting
